### ISSUE TITLE
Difference in results

### ISSUE THREAD

**Issue by gauraviiita** [LinghaoChan/HumanMAC#1]
Your work is adorable! I have a general question. In the results table, why does a single model result not outperform in all 15 cases of the H3.6M dataset or any other dataset? 
Here, your model outperforms most cases, but in some cases, the results of the previous approach are better than this model. What is the reason behind it?  
Also, in some actions, this model's results are far better than previous results, but in other actions, it is slightly better than the previous result. What is the reason for this? 
Your answer will be valuable to me
Thank you!

**Comment by LinghaoChan** [comment]
@gauraviiita Thanks for your attention👍. I present a general comment to your question first. We hope the "mask-completion" mechanism will ***open up a new perspective for the HMP task***. Therefore, the "SOTA" result on artificial metrics is not what we are really concerned about. Indeed, we claim the HumanMAC as a ***simple and significant*** baseline. Here are some detailed responses to your questions:

+ We did not test our model for 15 actions respectively. We test it on the full H36M dataset. ***As shown in Table 1, our ADE and FDE metrics outperform all baselines.*** The performance of different action categories does vary since different actions have different properties. In addition, some actions are inherently highly random, making prediction difficult. For example, waiting, people might walk and crouch randomly while waiting with no prior sign.  

+ If you are curious about why HumanMAC cannot outperform the baseline on APD, here are two reasons.  Firstly, the "diversity" of most baselines comes from failure cases. Please refer to section 5.2 on both Quantitative and Visualization analysis. Secondly, some baselines use the APD and ADE as their objective functions. It is unfair. If the predicted 50 candidate motions only are with 1 accurate motion and 49 failure cases, it will have low ADE and high APD. Therefore, this makes the comparison unfair and the artificial metrics are not reasonable. 

+ If you want to make our "mask-completion" fashion more fantastic, it cannot perform its strength in such an H36M dataset. The dataset is not large enough to perform its strength. Our future research will demonstrate the performance of the "mask-completion" fashion in more scenarios and larger-scale data😁. 

+ Using the "mask-completion" mechanism to predict motion has another advantage, it can retain the continuity of speed between observed and predicted frames. For example, the WalkingDog action in H36M. It is hard for previous models to model this kind of high-speed walking motion from the ground truth, yet our model can achieve this. 

Welcome for further discussion🤝.
